export const STEAM_LOGGED_IN = 'STEAM_LOGGED_IN';
export const STEAM_LOGOUT = 'STEAM_LOGOUT';
export const STEAM_LOAD_FROM_FIREBASE = 'STEAM_LOAD_FROM_FIREBASE';
export const STEAM_LOAD_FROM_FIREBASE_SUCCESS = 'STEAM_LOAD_FROM_FIREBASE_SUCCESS';
export const STEAM_LOAD_FROM_FIREBASE_FAIL = 'STEAM_LOAD_FROM_FIREBASE_FAIL';

export const UPDATE_USERS = 'UPDATE_USERS';

export const SET_GENERATED_TEAMS = 'SET_GENERATED_TEAMS';
export const GENERATE_TEAMS = 'GENERATE_TEAMS';
export const DELETE_GENERATE_TEAMS = 'DELETE_GENERATE_TEAMS';

export const SET_TOURNAMENT = 'SET_TOURNAMENT';
export const GENERATE_TOURNAMENT = 'GENERATE_TOURNAMENT';
export const DELETE_GENERATE_TOURNAMENT = 'DELETE_GENERATE_TOURNAMENT';
export const UPDATE_TOURNAMENT_LIST = 'UPDATE_TOURNAMENT_LIST';
