export const STEAM_LOGGED_IN = 'STEAM_LOGGED_IN';
export const STEAM_LOGOUT = 'STEAM_LOGOUT';
export const STEAM_LOAD_FROM_FIREBASE = 'STEAM_LOAD_FROM_FIREBASE';
export const STEAM_LOAD_FROM_FIREBASE_SUCCESS = 'STEAM_LOAD_FROM_FIREBASE_SUCCESS';
export const STEAM_LOAD_FROM_FIREBASE_FAIL = 'STEAM_LOAD_FROM_FIREBASE_FAIL';
